# Generated by Django 3.2.6 on 2021-09-03 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_thérapeutique',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Nom_thérapeutique', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Classe Thérapeutique ')),
            ],
        ),
        migrations.CreateModel(
            name='Dalete_echange',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, null=True, verbose_name='Nom utilisateur ')),
                ('Nom_C', models.CharField(max_length=20, null=True, verbose_name='Nom commercial ')),
                ('Nom_Ph', models.CharField(max_length=20, null=True, verbose_name='Pharmaci ')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dalete_product',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, null=True, verbose_name='Nom utilisateur ')),
                ('Nom_C', models.CharField(max_length=20, null=True, verbose_name='Nom commercial ')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dci',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Nom', models.TextField(max_length=20, primary_key=True, serialize=False, verbose_name='DCI ')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Nom_labo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Laboratoire ')),
                ('Tel', models.CharField(max_length=8, null=True, verbose_name='Téléphone ')),
                ('Adresse', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmaci',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Nom_Ph', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Pharmaci ')),
                ('Numéro_Inscription', models.CharField(max_length=50, null=True, verbose_name='Numéro Inscription ')),
                ('Tel', models.CharField(max_length=8, null=True, verbose_name='Téléphone ')),
                ('Adresse', models.CharField(max_length=50, null=True, verbose_name='Adresse ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Nom_C', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nom commercial ')),
                ('N_Lot', models.CharField(default='None', max_length=20, null=True, verbose_name='Numéro de lot ')),
                ('Dosage', models.CharField(max_length=20, null=True, verbose_name='Dosage ')),
                ('Forme', models.CharField(max_length=20, null=True, verbose_name='Forme ')),
                ('Présentation', models.CharField(max_length=150, null=True, verbose_name='Présentation ')),
                ('Conditionnement', models.CharField(max_length=20, null=True, verbose_name='Conditionnement ')),
                ('Spécification', models.CharField(max_length=20, null=True, verbose_name='Spécification ')),
                ('Tableau', models.CharField(max_length=20, null=True, verbose_name='Tableau ')),
                ('Durée_conservation', models.CharField(max_length=20, null=True, verbose_name='Durée Conservation ')),
                ('Price', models.DecimalField(decimal_places=3, max_digits=20, null=True, verbose_name='Price ')),
                ('Qte', models.PositiveIntegerField(null=True, verbose_name='Quantité ')),
                ('Classe_thérapeutique_Nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.classe_thérapeutique', verbose_name='Classe Thérapeutique ')),
                ('Dci_Nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dci', verbose_name='DCI ')),
                ('Labo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.laboratoire', verbose_name='Laboratoire ')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_classe',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Nom_classe', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Sous Classe ')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nom_C', models.CharField(max_length=20, null=True, verbose_name='Nom commercial ')),
                ('Qte', models.PositiveIntegerField(null=True, verbose_name='Quantité')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente_added',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Nom_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Product_edit',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Nom_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_added',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Nom_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Sous_classe_Nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sous_classe', verbose_name='Sous Classe '),
        ),
        migrations.CreateModel(
            name='Echange_added',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Nom_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('Nom_Ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pharmaci')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Echange',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Qte', models.PositiveIntegerField(null=True, verbose_name='Quantité ')),
                ('Nom_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('Nom_Ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pharmaci')),
            ],
        ),
    ]
