# Generated by Django 3.2.6 on 2021-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20210913_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dci',
            name='Nom',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='DCI '),
        ),
    ]
