# Generated by Django 3.2.6 on 2021-09-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20210913_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmaci',
            name='Numéro_Inscription',
        ),
    ]
